name: Build And Run Test on Mac

on:
  push:
    branches: [ main ]
  pull_request: 
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  COMPILER: /usr/local/opt/llvm/bin/clang++
  CFLAGS: -I /usr/local/include -I/usr/local/opt/llvm/include 
  CXXFLAGS: -I /usr/local/include -I/usr/local/opt/llvm/include 
  LDFLAGS: -L /usr/local/lib -L/usr/local/opt/llvm/lib 
  CXX: /usr/local/opt/llvm/bin/clang++


jobs:
      
  Build_And_Run_PyTest_Pip:
    name: Build and Run Unit Tests
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install gcc
      run: brew install gcc@8
        
    - name: Update Path
      run: |
        echo "brew --prefix llvm)/bin" >> $GITHUB_PATH
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: python3 -m pip install --upgrade wheel

    - name: Install pytest
      run: python -m pip install pytest

    - name: Install filepattern v1
      run: python -m pip install filepattern

    - name: Install filepattern2
      working-directory: ${{github.workspace}}
      run: python3 setup.py install

    - name: Run Unit Tests
      working-directory: ${{github.workspace}}
      run: python3 -m pytest tests/


  Build_and_Run_GTest:
    name: Build and Run GoogleTest
    runs-on: macos-11
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: anaconda-client-env
        python-version: 3.7
        channels: conda-forge
        auto-activate-base: false

    - name: Install Conda Dependencies
      run: |
        conda install compilers z5py libtiff boost nlohmann_json blosc pybind11 xtensor xsimd
    - name: Configure CMake
      run: cmake -B ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_CLI=ON -DCMAKE_PREFIX_PATH=$CONDA_PREFIX -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX

    - name: Build
      run: cmake --build ${{github.workspace}} --config ${{env.BUILD_TYPE}} --parallel 2

    - name: Run GTest Suite
      working-directory: ${{github.workspace}}
      # Execute tests.  
      run: ./tests/runAllTests  -C ${{env.BUILD_TYPE}}